export const ROUTES = {
  HOME: '/',
  LOBBY: '/lobby',
  LEADERBOARD: '/leaderboard',
  ROOM: `/room`,
  CUSTOM_WORD: `/room/custom-words`,
  KEYWORD: `/room/keyword`,
  DRAWING: `/room/drawing`,
  DISCUSSION: `/room/discussion`,
  GUESSING: `/room/guessing`,
  VOTING: `/room/voting`,
  VOTE_RESULT: `/room/vote-result`,
  ROUND_RESULT: `/room/round-result`,
  GAME_RESULT: `/room/game-result`,
  GUEST_ROOM: `/guest-room`,
  KEYWORD_REGISTER: `/room/keyword-register`,
}
