export const ROUTES = {
  HOME: '/',
  LOBBY: '/lobby',
  LEADERBOARD: '/leaderboard',
  WAITING: `/room/waiting`,
  CUSTOM_WORD: `/room/custom-words`,
  KEYWORD: `/room/keyword`,
  DRAWING: `/room/drawing`,
  DISCUSSION: `/room/discussion`,
  GUESSING: `/room/guessing`,
  VOTING: `/room/voting`,
  VOTE_RESULT: `/room/vote-result`,
  RESULT: `/room/result`,
  TEST: `/room/test`,
}
