import type { Player, Settings } from './types'

const SOCKET_MESSAGE_ERROR = 'SOCKET_MESSAGE_ERROR'

export { SOCKET_MESSAGE_ERROR }

export const COLORS = ['#000000', '#FFFFFF', '#d21717', '#00b300', '#0000FF']

export const DEFAULT_STROKE_WIDTH = 5
export const MAX_STROKE_WIDTH = 150
export const MIN_STROKE_WIDTH = 1

export const CONFETTI_DELAY = 5200

export const SYSTEM = { name: 'System', UUID: 'system' } as Player

export const DEFAULT_SETTINGS: Settings = {
  useCustomKeyword: true,
  rounds: 3,
  drawingTime: 60,
  maxPlayers: 8,
  octopusAmount: 2,
  isPublic: true,
  isCustomKeywordVoteOpen: true,
  customKeywordMinVotes: 2,
  lang: 'en',
  isFoolMode: false,
}

export const LANGUAGE_LABELS = {
  en: 'English',
  ko: '한국어',
}

export const ERRORS = {
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  PLAYER_NOT_IN_ROOM: 'PLAYER_NOT_IN_ROOM',
  PLAYER_UNREGISTERED: 'PLAYER_UNREGISTERED',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_CODE_ALREADY_EXISTS: 'ROOM_CODE_ALREADY_EXISTS',
  ROOM_CREATE_FAILED: 'ROOM_CREATE_FAILED',
  ROOM_ADD_PLAYER_FAILED: 'ROOM_ADD_PLAYER_FAILED',
  ROOM_PLAYER_NOT_FOUND: 'ROOM_PLAYER_NOT_FOUND',
  ROOM_HOST_NOT_FOUND: 'ROOM_HOST_NOT_FOUND',
  ROOM_UPDATE_FAILED: 'ROOM_UPDATE_FAILED',
  ONLY_HOST_CAN_CHANGE_SETTINGS: 'ONLY_HOST_CAN_CHANGE_SETTINGS',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  ROUND_INIT_ERROR: 'ROUND_INIT_ERROR',
  GAME_ALREADY_IN_PROGRESS: 'GAME_ALREADY_IN_PROGRESS',
  GAME_CREATE_FAILED: 'GAME_CREATE_FAILED',
  ONLY_HOST_CAN_START_GAME: 'ONLY_HOST_CAN_START_GAME',
  CANVAS_NOT_FOUND: 'CANVAS_NOT_FOUND',
  CANVAS_CREATE_FAILED: 'CANVAS_CREATE_FAILED',
  CANVAS_NOT_ALLOWED: 'CANVAS_NOT_ALLOWED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NO_ACCESS_TO_PRIVATE_ROOM_ERROR: 'NO_ACCESS_TO_PRIVATE_ROOM_ERROR',
} as const
